server:
  port: 8888
spring:
  profiles:
    active: dev
  freemarker:
    cache: false
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
    view:
     prefix: /templates/
     suffix: .ftl
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

logging:
  file: spring.log
  level:
    com:
      hubu:
        learn: DEBUG
      jdbc: ERROR
      jdbc.resultsettable: ERROR
      org:
        springframework: INFO
        springframework.security: INFO
      root: INFO

pagehelper:
  helperDialect: h2
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true

