spring:
  datasource:
    data: classpath:db/data.sql
    schema: classpath:db/schema.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:D:\JavaProgram\H2Database/test;MODE=MySql;DB_CLOSE_DELAY=-1
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true